# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\get_base_url.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetBaseUrl(HttpRunner):

    config = Config("get_test").base_url("http://49.235.92.12:8201")

    teststeps = [
        Step(
            RunRequest("get_test")
            .get("/api/v1/goods")
            .with_params(**{"page": 1, "size": 2})
        ),
    ]


if __name__ == "__main__":
    TestCaseGetBaseUrl().test_start()
