# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\part1\login.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):
    @pytest.mark.parametrize("param", Parameters({"user-psw": "${get_user_psw(3)}"}))
    def test_start(self, param):
        super().test_start(param)

    config = Config("用例描述").base_url("http://49.235.92.12:8201").export(*["token"])

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
            .assert_equal("body.username", "$user")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
