# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\part1\register.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegister(HttpRunner):

    config = (
        Config("用户注册测试用例")
        .variables(**{"user": "${register_user()}", "psw": "123456"})
        .base_url("http://49.235.92.12:8201")
    )

    teststeps = [
        Step(
            RunRequest("step-注册")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw"})
        ),
    ]


if __name__ == "__main__":
    TestCaseRegister().test_start()
