# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcases\part1\upload.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUpload(HttpRunner):

    config = Config("上传文件").base_url("http://49.235.92.12:8201")

    teststeps = [
        Step(
            RunRequest("upload file")
            .post("http://httpbin.org/upload")
            .with_headers(**{"Cookie": "session=AAA-BBB-CCC"})
            .upload(**{"file": "data/pic.jpg", "field1": "value1", "field2": "value2"})
            .validate()
            .assert_equal("status_code", 200)
        ),
    ]


if __name__ == "__main__":
    TestCaseUpload().test_start()
