# NOTE: Generated By HttpRunner v3.1.4
# FROM: testcases\userinfo.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseUserinfo(HttpRunner):

    config = (
        Config("用户信息")
        .variables(**{"user": "test", "psw": "123456"})
        .base_url("http://49.235.92.12:8201")
    )

    teststeps = [
        Step(
            RunRequest("用户登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("用户信息")
            .post("/api/v1/userinfo")
            .with_headers(**{"Authorization": "token $token"})
            .with_json(
                {"name": "$user", "sex": "M", "age": 20, "email": "283340479@qq.com"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseUserinfo().test_start()
