# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcase/login/login_fail.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginFail(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {"user-psw": [["xxyyzz", "123456"], ["test123", "111111"], ["", ""]]}
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = Config("用例描述-无效登录参数化").base_url("${ENV(base_url)}")

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 3003)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginFail().test_start()
