# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcase/login/login_success.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginSuccess(HttpRunner):

    config = (
        Config("用例描述-无效登录参数化")
        .variables(**{"user": "test", "psw": 123456})
        .base_url("${ENV(base_url)}")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.username", "$user")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginSuccess().test_start()
