# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcase/part1/login_hook.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginHook(HttpRunner):

    config = (
        Config("用例描述-登录用例")
        .variables(**{"user": "test1", "psw": "123456"})
        .base_url("http://49.235.92.12:8201")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("step-登录")
            .setup_hook("${setup_hook()}")
            .setup_hook("${request_sign($request)}")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .teardown_hook("${teardown_hook()}")
            .teardown_hook("${response_status($response)}")
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
            .assert_equal("body.username", "$user")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginHook().test_start()
